#############################################################################
#   CA Server Client YAML file for the CA Server Admin
#   Changes to the CSR
#############################################################################

#############################################################################
# Client Configuration
#############################################################################

# URL of the Fabric-ca-server (default: http://localhost:7054)
url: http://192.168.50.40:7054

# Membership Service Provider (MSP) directory
# This is useful when the client is used to enroll a peer or orderer, so
# that the enrollment artifacts are stored in the format expected by MSP.
mspdir: msp

#############################################################################
#    TLS section for secure socket connection
#
#  certfiles - PEM-encoded list of trusted root certificate files
#  client:
#    certfile - PEM-encoded certificate file for when client authentication
#    is enabled on server
#    keyfile - PEM-encoded key file for when client authentication
#    is enabled on server
#############################################################################
tls:
  # TLS section for secure socket connection
  certfiles:
  client:
    certfile:
    keyfile:

#############################################################################
#
#############################################################################
csr:
  cn: admin
  serialnumber:
  names:
    - C: US
      ST: "New York"
      L:  "Loc"
      O:  one
      OU: "Fabric"
  hosts:
     - lastonevm
     - 192.168.50.40

#############################################################################
#  Registration section used to register a new identity with fabric-ca server
#############################################################################
id:
  # Must override the name
  name: admin
  # By default the type is set to be user
  type: user
  # Default org is acme - make sure the org is set up in CA server :-)
  affiliation: one
  # Set to max of 2
  maxenrollments: -1


#############################################################################
#  Enrollment section used to enroll an identity with fabric-ca server
#
#  profile - Name of the signing profile to use in issuing the certificate
#  label - Label to use in HSM operations
#############################################################################
enrollment:
  profile:
  label:

#############################################################################
# Name of the CA to connect to within the fabric-ca server
#############################################################################
caname: one-ca

#############################################################################
# BCCSP (BlockChain Crypto Service Provider) section allows to select which
# crypto implementation library to use
#############################################################################
bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            # The directory used for the software file-based keystore
            keystore: msp/keystore

